analyzer:
  errors:
    library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add any additional linter rules you want to apply to your project.
